### ISSUE TITLE
Protobuf error when reading osm-pbf file

### ISSUE THREAD

**Issue by xivk** [systemed/tilemaker#40]
I'm getting an error when loading a custom-made pbf file. I converted a big dataset of bustops into osm-data and then built an osm-pbf file. I'm able to read/write this file with both osmosis and josm but it fails when loading it into tilemaker. Just to make sure the pbf is using dense nodes I recreated the file using osmosis.

```
Reading stops1.osm.pbf
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "BlobHeader" because it is missing required fields: type, datasize
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception during zlib decompression: (-5) 
Aborted (core dumped)
```

A possible cause: there are no ways or relations in this file...

The actual file: https://www.dropbox.com/s/tttfctupw4okmhv/stops.osm.pbf?dl=0

**Comment by xivk** [comment]
I created a new file by adding one way and one relation and things work fine.

**Comment by longlostbro** [comment]
I have this same problem. Are you saying you added a way and a relation to the osm.pbf? or to the config.json?

**Comment by xivk** [comment]
To the osm.pbf, things seemed to fail when there are no ways or relations...

**Comment by pnull** [comment]
@systemed this is a really old issue, I know. But still: Is there any chance you'll fix this anytime soon?

**Comment by systemed** [comment]
Can you post your file, and explain how you generated it? The error says that BlobHeader is missing `type` and `datasize` which are required fields (see https://wiki.openstreetmap.org/wiki/PBF_Format) so I'm not 100% convinced it's tilemaker which is at fault here.

**Comment by pnull** [comment]
@systemed Of course... I used a regional .osm.pbf dump for latest OSM data for France: https://download.geofabrik.de/europe/france-latest.osm.pbf

**Comment by systemed** [comment]
Hmmm. Are you able to reproduce it with anything smaller? Would rather not spin up a many-GB machine just so I have enough memory to load the 8 gazillion cadastre buildings in the France extract ;)

**Comment by pnull** [comment]
We only generate a small amount of tiles at a specific zoom level. Works with a machine with not much memory without issues. Can you give me an email address where I can send the config? I'd rather not post it here.

**Comment by systemed** [comment]
Sure, richard@systemeD.net

**Comment by pnull** [comment]
You should received it. 😄

**Comment by systemed** [comment]
I have, but unfortunately testing against france-latest.osm.pbf is rather slow - currently on block 42500 and still processing...

**Comment by systemed** [comment]
I've pushed a fix for the original issue @xivk was encountering, but I'm 99% sure that's not the same issue as france-latest.osm.pbf I'm afraid.

**Comment by xivk** [comment]
Thanks @systemed 👍

**Comment by pnull** [comment]
@systemed have you tested your fix with the France file?

**Comment by systemed** [comment]
I'm doing so at the moment, but like I say, it takes over an hour for me to run it on so large a file. I don't think it'll fix it - the original issue (and the fix) were for files without any ways in, and france-latest.osm.pbf clearly has ways in it!

**Comment by systemed** [comment]
May have identified the issue, waiting for it to complete.

**Comment by systemed** [comment]
france.osm.pbf issue fixed with https://github.com/systemed/tilemaker/commit/e8975fe20960b6626a8c6ac3bfbe5049cb2aec7a . The .pbf is so massive (3.7GB) that it was overflowing the `int` that tilemaker used to store the position in the file where the ways start. I've now replaced the `int` with a `long long`.

Generally with very large .pbfs I'd recommend using osmfilter and osmconvert first to eliminate any information that you don't need. (Particularly in the case of France, which has millions of building geometries that you may not need.) This will reduce tilemaker's memory footprint and therefore reduce the likelihood of swap.

Thanks for the report! :)

**Comment by pnull** [comment]
@systemed Unfortunately, I'm still facing the same issue. It still breaks with the same error for me.

What can I give or send you to maybe track my issue down?

**Comment by systemed** [comment]
What stage has it reached when that happens? What block number is it at? (I got to 54712 before ctrl-C-ing because it was taking forever.)

**Comment by pnull** [comment]
It counts until like ~54600 before it breaks. It counts up very fast - so I can't say the correct number, unfortunately.

**Comment by systemed** [comment]
Really really really stupid question, but you have done a `make` and `make install`? I know it's obvious but...

**Comment by pnull** [comment]
i did a `make clean && make` after `git pull origin master`. Here's how the ls looks like:

![image](https://user-images.githubusercontent.com/872019/35705129-e1392802-07a1-11e8-8e24-3061cbb079f4.png)

So, yes. I am 100% sure.

**Comment by systemed** [comment]
Hm. All I can suggest is putting some debug output around line 576 of `tilemaker.cpp` and seeing what it comes up with. Something like:

````
			if (infile.eof()) {
cout << endl << "Reached end of file" << endl;
				if (!checkedRelations) {
					checkedRelations = true;
				} else {
cout << endl << "Read everything, exiting read loop" << endl;
					break;
				}
			    if (wayPosition==-1) {
					cout << ".pbf does not contain any ways" << endl;
					break;
				}
cout << endl << "Rewinding to " << wayPosition << endl;
				infile.clear();
				infile.seekg(wayPosition);
				continue;
			}
````

where the unindented lines are new. Recompile and rerun and see what it comes up with. At the very least it should tell us where it's breaking, and if it's as a result of rewinding through the file to go back to the ways on the second pass.

**Comment by pnull** [comment]
Okay. Did the changes you mentioned. Here's the result:

```
osrm@map-1:~/tilemaker$ vi src/tilemaker.cpp
osrm@map-1:~/tilemaker$ make clean
rm -f tilemaker src/tilemaker.o
osrm@map-1:~/tilemaker$ make -j8
g++ -O3 -Wall -Wno-unknown-pragmas -Wno-sign-compare -std=c++11 -pthread  -o src/tilemaker.o -c src/tilemaker.cpp -I/usr/local/include -isystem ./include -I./src -I/usr/local/include/lua5.1 -I/usr/include/lua5.1
g++ -O3 -Wall -Wno-unknown-pragmas -Wno-sign-compare -std=c++11 -pthread  -o tilemaker include/osmformat.pb.o include/vector_tile.pb.o clipper/clipper.o src/mbtiles.o src/pbf_blocks.o src/coordinates.o src/osm_store.o src/helpers.o src/output_object.o src/read_shp.o src/osm_object.o src/write_geometry.o src/tilemaker.o -I/usr/local/include -isystem ./include -I./src -I/usr/local/include/lua5.1 -I/usr/include/lua5.1 -L/usr/local/lib -lz -llua5.1 -lboost_program_options -lsqlite3 -lboost_filesystem -lboost_system -lprotobuf -lshp
osrm@map-1:~/tilemaker$ tilemaker --input france-latest.osm.pbf --output mapmatching.mbtiles --threads=12
Layer r1 (z16-16)
Layer r2 (z16-16)
Layer r3 (z16-16)
Layer r4 (z16-16)
Layer pi (z16-16)
Layer hn (z16-16)
Reading france-latest.osm.pbf
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "BlobHeader" because it is missing required fields: type, datasize
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception during zlib decompression: (-5)
Aborted
```

Unfortunately, there's nothing to see... 😞

**Comment by pnull** [comment]
Forget my last post. I found my mistake. Issues is resolved for me...

Thank you so much for your time and effort you've put into helping me!!

**Comment by systemed** [comment]
Excellent - really glad it works!

**Comment by aenkirch** [comment]
I have the same error with this pbf file ( https://my.pcloud.com/publink/show?code=XZ5cWn7ZAAVSaGFw0OQFFL7wmbSPjRghfVHX ), can someone help me with this please ?

**Comment by aenkirch** [comment]
@systemed I have the same error with this pbf file ( https://ln.sync.com/dl/604a94a10/c6gmwwjy-3p9iwgxn-t8d37xj3-4xgmms6e ), can you help me with this please ?

**Comment by systemed** [comment]
Yes, when I have a spare moment - @-ing me won't make me magically support you any faster unless you're prepared to do my day job for me ;)

**Comment by aenkirch** [comment]
Haha no problem, I'll be waiting :)

**Comment by aenkirch** [comment]
Hi ! Have you eventually had a spare time to have a look on the problem ?
